// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	domain "project/internal/auth/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// Mockstore is a mock of store interface.
type Mockstore struct {
	ctrl     *gomock.Controller
	recorder *MockstoreMockRecorder
}

// MockstoreMockRecorder is the mock recorder for Mockstore.
type MockstoreMockRecorder struct {
	mock *Mockstore
}

// NewMockstore creates a new mock instance.
func NewMockstore(ctrl *gomock.Controller) *Mockstore {
	mock := &Mockstore{ctrl: ctrl}
	mock.recorder = &MockstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstore) EXPECT() *MockstoreMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *Mockstore) CreateUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockstoreMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Mockstore)(nil).CreateUser), ctx, user)
}

// GetUser mocks base method.
func (m *Mockstore) GetUser(ctx context.Context, email string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockstoreMockRecorder) GetUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*Mockstore)(nil).GetUser), ctx, email)
}

// Mockblacklist is a mock of blacklist interface.
type Mockblacklist struct {
	ctrl     *gomock.Controller
	recorder *MockblacklistMockRecorder
}

// MockblacklistMockRecorder is the mock recorder for Mockblacklist.
type MockblacklistMockRecorder struct {
	mock *Mockblacklist
}

// NewMockblacklist creates a new mock instance.
func NewMockblacklist(ctrl *gomock.Controller) *Mockblacklist {
	mock := &Mockblacklist{ctrl: ctrl}
	mock.recorder = &MockblacklistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockblacklist) EXPECT() *MockblacklistMockRecorder {
	return m.recorder
}

// Revoke mocks base method.
func (m *Mockblacklist) Revoke(ctx context.Context, tokenID string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tokenID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockblacklistMockRecorder) Revoke(ctx, tokenID, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*Mockblacklist)(nil).Revoke), ctx, tokenID, ttl)
}

// MocktokenBuilder is a mock of tokenBuilder interface.
type MocktokenBuilder struct {
	ctrl     *gomock.Controller
	recorder *MocktokenBuilderMockRecorder
}

// MocktokenBuilderMockRecorder is the mock recorder for MocktokenBuilder.
type MocktokenBuilderMockRecorder struct {
	mock *MocktokenBuilder
}

// NewMocktokenBuilder creates a new mock instance.
func NewMocktokenBuilder(ctrl *gomock.Controller) *MocktokenBuilder {
	mock := &MocktokenBuilder{ctrl: ctrl}
	mock.recorder = &MocktokenBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenBuilder) EXPECT() *MocktokenBuilderMockRecorder {
	return m.recorder
}

// BuildAccessToken mocks base method.
func (m *MocktokenBuilder) BuildAccessToken(userID uuid.UUID, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAccessToken", userID, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildAccessToken indicates an expected call of BuildAccessToken.
func (mr *MocktokenBuilderMockRecorder) BuildAccessToken(userID, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAccessToken", reflect.TypeOf((*MocktokenBuilder)(nil).BuildAccessToken), userID, expiration)
}
